version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: assignment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: socialmediadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: assignment-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
