spring.application.name=assignment

# Postgres setup

spring.datasource.url=jdbc:postgresql://localhost:5432/socialmediadb
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver